config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks

  # get 'home/index'
  get 'home/about'
  # To whom who wants to see the Thinker-Guy >> uncomment route bellow..

  # root 'home#index'
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    # @task = Task.new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    # @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to tasks_path, notice: "Unauthorized! Access Denied.." if @task.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:first_item, :created, :title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Rails☘Folks', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About⧁Us', home_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Tasks', tasks_path, class: 'nav-link' %>
      </li>
      <!-- <li class="nav-item">
        <%= link_to 'New⧁Task', new_task_path, class: 'nav-link' %>
      </li> -->

      <!-- Users -->
      <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to 'New⧁Task', new_task_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign⧁Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit', edit_user_registration_path, class: 'nav-link' %>
      </li>

      <% else %>

      <li class="nav-item">
        <%= link_to 'Sign⧁Up', new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign⧁In', new_user_session_path, class: 'nav-link' %>
      </li>

      <% end %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://duckduckgo.com">D*ckD*ckGo</a>
          <a class="dropdown-item" href="https://search.yahoo.com">Yah*o!</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="https://google.com">G**gle</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="No Spiders here.. 🕷" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">🕸 Search</button>
    </form>
  </div>
</nav>

<div class="footer">
  <p></p>
  <p>Created by <a id="link" href="https://github.com/dantes47/railsfolks">DannyⓒElmob</a> for << <a href="https://rubygarage.org">RubyGarage❦</a></p>
</div>

app/views/home/about.html.erb
<div class="container">
    <h1>It's all about Cats, you know..</h1>

    <p>
        <img src="https://t1.pixers.pics/img/wall-murals-british-cat-looking-up-through-hole-in-paper-great-britain-flag.png?H4sIAAAAAAAAA41PW27DIBC8ji3hLBhc1hwgvzmCtcaQuPEDAW3anr5YVb6qSt1dad8zGnjbEnkH1m3ZRVjnaVoc-HkpXTLRpfnLVZxprmpTpkvFOa_N_u6ijXuoGilYg8hQ9Uz3bW0eVB5XivfqlnNIBiDJU5g_ClpJNoFdE7RcaOAv0PWdItV6tFOvh0zBZWruD5oi5VPYrowfXhsKYfkcoiusyQ20hBv9H15y3blufML_ZqmfMhXnTB3y_F4k5OrYwR88PzWUczhfQCmQCFhCHqPhfFFKYjE5oFejFWTHVkrlETsxokXpRy2Ik8DTa7h-A6XjSiqFAQAA" alt="cat">
    </p>
</div>

app/views/home/index.html.erb
<div class="container">
  <h2>That's not a 'Big Picture'.. Yet!</h2>
    <p>Let's think more out of the Box..</p>
    <p>
        <img src="http://vegawoodworking.com/wp-content/uploads/2014/09/thinking-man1.png" alt="think">
    </p>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Rails Folks App</title>
    <link rel="icon" href="http://icons.iconarchive.com/icons/iconshock/real-vista-development/256/ruby-icon.png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
      <br>
    <div class="container">

      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>

    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <% form.label :first_item %>
    <%= form.text_field :first_item, class: "form-control", placeholder: "First item" %>
    <% form.label :created %>
    <p></p>
    <%= form.check_box :created, class: "form-check-label", type: "checkbox" %>
  </div>
  <div class="field form-group">
    <% form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="field form-group">
    <% form.label :content %>
    <%= form.text_area :content, class: "form-control", rows: "13", placeholder: "Content" %>
  </div>
  <div class="field form-group">
    <% form.label :title %>
    <%= form.number_field :user_id, class: "form-control", value: current_user.id, id: :task_user_id, type: :hidden %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>
<br>
<%= render 'form', task: @task %>
<br>
<%= link_to 'Show', @task, class: 'btn btn-info' %>
<%= link_to 'Back', tasks_path, class: 'btn btn-secondary' %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <h1>Tasks<small class='h'>❦</small>List</h1>

  <div class="panel panel-default">
    <table class="table table-curved table-outline-success table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Main⧁Title</th>
        <th>Created</th>
        <th>Review</th>
        <th>Content</th>
        <th>ID</th>
        <th colspan="3">CRUD⧁Area</th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <!-- To whom, who wants to see All the Users Task-Tables: Uncomment those logic bellow | Dannyⓒ -->

        <% #if task.user == current_user %>
        <tr>
          <td><%= task.first_item %></td>
          <td><%= check_box_tag 'task', '1', task.created, :disabled => true, class: 'check' %></td>
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= task.user_id %></td>
          <td><%= link_to 'Show', task, class: 'btn btn-outline-info' %></td>
          <td><%= link_to 'Edit', edit_task_path(task), class: 'btn btn-outline-warning' %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
        </tr>
        <% #end %>

      <% end %>
    </tbody>
  </table>
  </div>

  <br>

  <%= link_to 'New Task', new_task_path, class: 'btn btn-outline-dark btn-block' %>
<% else %>

  <div class="container">
    <h2>That's not a 'Big Picture'.. Yet!</h2>
      <p>Let's think more out of the Box..</p>
      <p>
          <img src="http://vegawoodworking.com/wp-content/uploads/2014/09/thinking-man1.png" alt="think">
      </p>
  </div>

<% end %>

app/views/tasks/new.html.erb
<h1>Add New Task</h1>
<p></p>
<%= render 'form', task: @task %>
<p></p>
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="jumbotron">
<h4 class="display-6">
| <%= @task.first_item %> |
<br>
| <%= @task.created %>    |
</h4>
<p>
| <%= @task.title %>      |
| <%= @task.content %>    |
</p>
<br>
<hr class="my-6">
<br>
<%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-warning' %>
<%= link_to 'Back', tasks_path, class: 'btn btn-success' %>

</div>